


	PLUGIN_URL=
	PLUGIN_HTTP_METHOD
	PLUGIN_VALID_RESPONSE_CODES
	PLUGIN_TIMEOUT
	PLUGIN_VALID_RESPONSE_BODY
	PLUGIN_WRAP_AS_MULTIPART
	PLUGIN_OUTPUT_FILE
	PLUGIN_IGNORE_SSL
	PLUGIN_REQUEST_BODY
	PLUGIN_LOG_RESPONSE
	PLUGIN_QUIET
	PLUGIN_CONTENT_TYPE
	PLUGIN_HEADERS
	PLUGIN_AUTH_BASIC
	PLUGIN_ACCEPT_TYPE


	PLUGIN_TIMEOUT=10

  PLUGIN_URL=https://reqres.in/api/users?page=2 \
	PLUGIN_HTTP_METHOD="GET" \
	PLUGIN_HEADERS=",Content-Type: application/json, a:b" \
	go run main.go